@file:Suppress("unused")

package com.jonolds.bugreportproject.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0053DA)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDBE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF00174B)
val md_theme_light_secondary = Color(0xFF345CA8)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD9E2FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001A43)
val md_theme_light_tertiary = Color(0xFF824790)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFDD6FF)
val md_theme_light_onTertiaryContainer = Color(0xFF340042)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF001159)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF001159)
val md_theme_light_surfaceVariant = Color(0xFFE2E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
val md_theme_light_outline = Color(0xFF757680)
val md_theme_light_inverseOnSurface = Color(0xFFF0EFFF)
val md_theme_light_inverseSurface = Color(0xFF152778)
val md_theme_light_inversePrimary = Color(0xFFB4C5FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0053DA)
val md_theme_light_surfaceTintColor = Color(0xFF0053DA)



val temp = Color(0xFFFF008B)

val md_theme_dark_primary = Color(0xFFB4C5FF)
val md_theme_dark_onPrimary = Color(0xFF002A77)
val md_theme_dark_primaryContainer = Color(0xFF003EA7)
val md_theme_dark_onPrimaryContainer = Color(0xFFDBE1FF)
val md_theme_dark_secondary = Color(0xFFAFC6FF)
val md_theme_dark_onSecondary = Color(0xFF002D6C)
val md_theme_dark_secondaryContainer = Color(0xFF14448F)
val md_theme_dark_onSecondaryContainer = Color(0xFFD9E2FF)
val md_theme_dark_tertiary = Color(0xFFF4AEFF)
val md_theme_dark_onTertiary = Color(0xFF4F155D)
val md_theme_dark_tertiaryContainer = Color(0xFF682E76)
val md_theme_dark_onTertiaryContainer = Color(0xFFFDD6FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001159)
val md_theme_dark_onBackground = Color(0xFFDEE1FF)
val md_theme_dark_surface = Color(0xFF001159)
val md_theme_dark_onSurface = Color(0xFFDEE1FF)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
val md_theme_dark_outline = Color(0xFF8F909A)
val md_theme_dark_inverseOnSurface = Color(0xFF001159)
val md_theme_dark_inverseSurface = Color(0xFFDEE1FF)
val md_theme_dark_inversePrimary = Color(0xFF0053DA)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB4C5FF)
val md_theme_dark_surfaceTintColor = Color(0xFFB4C5FF)


object ClubhouseColors {

    val steelGrey = Color(0xFF424959)
    val darkSteelGrey = Color(0xFF323846)
    val seedBlue = Color(0xFF3572FF)
    val seedDarkBlue = Color(0xFF0043DD)
    val seedGreen = Color(0xFF7DFF74)
    val darkRed = Color(0xFFB90000)
    val darkGreen = Color(0xFF009B03)
    val purple = Color(0xFFBD00BA)
    val lightYellow = Color(0xFFFBFF80)

}
