@file:UseSerializers(SnapshotStateListSerializer::class, MutableStateSerializer::class, StateSerializer::class,
	SnapshotStateListSerializerEmptyIfNull::class)
package com.jonolds.bugreportproject.tests.tabrowtest

import androidx.compose.runtime.Stable
import androidx.compose.runtime.snapshots.SnapshotStateList
import androidx.compose.runtime.toMutableStateList
import androidx.lifecycle.ViewModel
import com.jonolds.bugreportproject.model.DiscsItemObservable
import com.jonolds.bugreportproject.model.TracksItemObservable
import com.jonolds.bugreportproject.utils.json
import com.jonolds.bugreportproject.utils.move
import com.jonolds.bugreportproject.utils.serializers.MutableStateSerializer
import com.jonolds.bugreportproject.utils.serializers.SnapshotStateListSerializer
import com.jonolds.bugreportproject.utils.serializers.SnapshotStateListSerializerEmptyIfNull
import com.jonolds.bugreportproject.utils.serializers.StateSerializer
import kotlinx.serialization.UseSerializers
import kotlinx.serialization.json.Json

@Stable
class TabRowTestVM: ViewModel() {

	private val _discs: MutableList<DiscsItemObservable> = discs4.toMutableStateList()
	val discs: List<DiscsItemObservable> = _discs


	fun move(from: Int, to: Int) {
		_discs.move(from, to)
	}

	fun removeTrack(key: String) {
		val disc = discs.first { it.tracks.any { it.position == key } }
		val track = disc.tracks.first { it.position == key }
		disc.tracks.remove(track)
	}

	fun removeByIndex(i: Int) {
		_discs.removeAt(i)
	}


}


internal val discs4 by lazy {
	json.decodeFromString<List<DiscsItemObservable>>("""[
{"discTitle":"Disc 1","tracks":[{"position":"1","title":"I Had Too Much to Dream (Last Night)","artistCredit":"The Electric Prunes"},{"position":"2","title":"Dirty Water","artistCredit":"The Standells"},{"position":"3","title":"Night Time","artistCredit":"The Strangeloves"},{"position":"4","title":"Lies","artistCredit":"The Knickerbockers"},{"position":"5","title":"Respect","artistCredit":"The Vagrants"},{"position":"6","title":"A Public Execution","artistCredit":"Mouse and the Traps"},{"position":"7","title":"No Time Like the Right Time","artistCredit":"The Blues Project"},{"position":"8","title":"Oh Yeah","artistCredit":"The Shadows of Knight"},{"position":"9","title":"Pushin' Too Hard","artistCredit":"The Seeds"},{"position":"10","title":"Moulty","artistCredit":"The Barbarians"},{"position":"11","title":"Don't Look Back","artistCredit":"The Remains"},{"position":"12","title":"An Invitation to Cry","artistCredit":"The Magicians"},{"position":"13","title":"Liar, Liar","artistCredit":"The Castaways"},{"position":"14","title":"You're Gonna Miss Me","artistCredit":"13th Floor Elevators"},{"position":"15","title":"Psychotic Reaction","artistCredit":"Count Five"},{"position":"16","title":"Hey Joe","artistCredit":"The Leaves"},{"position":"17","title":"Romeo and Juliet","artistCredit":"Michael and the Messengers"},{"position":"18","title":"Sugar and Spice","artistCredit":"The Cryan' Shames"},{"position":"19","title":"Baby Please Don't Go","artistCredit":"The Amboy Dukes"},{"position":"20","title":"Tobacco Road","artistCredit":"The Blues Magoos"},{"position":"21","title":"Let's Talk About Girls","artistCredit":"The Chocolate Watch Band"},{"position":"22","title":"Sit Down, I Think I Love You","artistCredit":"The Mojo Men"},{"position":"23","title":"Run, Run, Run","artistCredit":"The Third Rail"},{"position":"24","title":"My World Fell Down","artistCredit":"Sagittarius"},{"position":"25","title":"Open My Eyes","artistCredit":"Nazz"},{"position":"26","title":"Farmer John","artistCredit":"The Premiers"},{"position":"27","title":"It's A‐Happening","artistCredit":"The Magic Mushrooms"}]}
,{"discTitle":"Disc 2","tracks":[{"position":"1","title":"Talk Talk","artistCredit":"The Music Machine"},{"position":"2","title":"Last Time Around","artistCredit":"The Del‐Vetts"},{"position":"3","title":"Nobody but Me","artistCredit":"The Human Beinz"},{"position":"4","title":"Journey to Tyme","artistCredit":"Kenny & the Kasuals"},{"position":"5","title":"No Friend of Mine","artistCredit":"The Sparkles"},{"position":"6","title":"Outside Chance","artistCredit":"The Turtles"},{"position":"7","title":"Action Woman","artistCredit":"The Litter"},{"position":"8","title":"Spazz","artistCredit":"The Elastik Band"},{"position":"9","title":"Sweet Young Thing","artistCredit":"The Chocolate Watch Band"},{"position":"10","title":"Incense & Peppermints","artistCredit":"Strawberry Alarm Clock"},{"position":"11","title":"I Ain't No Miracle Worker","artistCredit":"The Brogues"},{"position":"12","title":"7 & 7 Is","artistCredit":"Love"},{"position":"13","title":"Time Won't Let Me","artistCredit":"The Outsiders"},{"position":"14","title":"Going All the Way","artistCredit":"The Squires"},{"position":"15","title":"I'm Gonna Make You Mine","artistCredit":"The Shadows of Knight"},{"position":"16","title":"The Trip","artistCredit":"Kim Fowley"},{"position":"17","title":"Can't Seem to Make You Mine","artistCredit":"The Seeds"},{"position":"18","title":"Why Do I Cry","artistCredit":"The Remains"},{"position":"19","title":"Laugh, Laugh","artistCredit":"The Beau Brummels"},{"position":"20","title":"The Little Black Egg","artistCredit":"The Nightcrawlers"},{"position":"21","title":"I Wonder","artistCredit":"The Gants"},{"position":"22","title":"I See the Light","artistCredit":"The Five Americans"},{"position":"23","title":"Who Do You Love","artistCredit":"The Woolies"},{"position":"24","title":"Double Shot (of My Baby's Love)","artistCredit":"The Swingin' Medallions"},{"position":"25","title":"Live","artistCredit":"The Merry‐Go?d"},{"position":"26","title":"Steppin' Out","artistCredit":"Paul Revere and the Raiders"},{"position":"27","title":"Diddy Wah Diddy","artistCredit":"Captain Beefheart & His Magic Band"},{"position":"28","title":"Strychnine","artistCredit":"The Sonics"},{"position":"29","title":"Little Girl","artistCredit":"The Syndicate of Sound"},{"position":"30","title":"(We Ain't Got) Nothin' Yet","artistCredit":"The Blues Magoos"},{"position":"31","title":"Shape of Things to Come","artistCredit":"Max Frost & the Troopers"}]}
,{"discTitle":"Disc 3","tracks":[{"position":"1","title":"Let It Out (Let It All Hang Out)","artistCredit":"The Hombres"},{"position":"2","title":"Fight Fire","artistCredit":"The Golliwogs"},{"position":"3","title":"At the River's Edge","artistCredit":"The New Colony Six"},{"position":"4","title":"Jack of Diamonds","artistCredit":"The Daily Flash"},{"position":"5","title":"Follow Me","artistCredit":"Lyme & Cybelle"},{"position":"6","title":"It's Cold Outside","artistCredit":"The Choir"},{"position":"7","title":"Beg, Borrow and Steal","artistCredit":"The Rare Breed"},{"position":"8","title":"She's About a Mover","artistCredit":"The Sir Douglas Quintet"},{"position":"9","title":"Little Bit O'Soul","artistCredit":"The Music Explosion"},{"position":"10","title":"Put the Clock Back on the Wall","artistCredit":"The 'E' Types"},{"position":"11","title":"Falling Sugar","artistCredit":"The Palace Guard"},{"position":"12","title":"Run, Run, Run","artistCredit":"The Gestures"},{"position":"13","title":"I Need You","artistCredit":"The Rationals"},{"position":"14","title":"Knock, Knock","artistCredit":"The Humane Society"},{"position":"15","title":"Primitive","artistCredit":"The Groupies"},{"position":"16","title":"Psycho","artistCredit":"The Sonics"},{"position":"17","title":"So What!!","artistCredit":"The Lyrics"},{"position":"18","title":"You Must Be a Witch","artistCredit":"The Lollipop Shoppe"},{"position":"19","title":"A Question of Temperature","artistCredit":"The Balloon Farm"},{"position":"20","title":"Maid of Sugar ‐ Maid of Spice","artistCredit":"Mouse and the Traps"},{"position":"21","title":"You Ain't Tuff","artistCredit":"The Uniques"},{"position":"22","title":"Sometimes Good Guys Don't Wear White","artistCredit":"The Standells"},{"position":"23","title":"She's My Baby","artistCredit":"The Mojo Men"},{"position":"24","title":"Story of My Life","artistCredit":"Unrelated Segments"},{"position":"25","title":"I'm Five Years Ahead of My Time","artistCredit":"The Third Bardo"},{"position":"26","title":"Mirror of Your Mind","artistCredit":"We the People"},{"position":"27","title":"Bad Little Woman","artistCredit":"The Shadows of Knight"},{"position":"28","title":"Double Yellow Line","artistCredit":"The Music Machine"},{"position":"29","title":"Optical Sound","artistCredit":"The Human Expression"},{"position":"30","title":"Journey to the Center of the Mind","artistCredit":"The Amboy Dukes"}]}
,{"discTitle":"Disc 4","tracks":[{"position":"1","title":"Are You Gonna Be there (at the Love In)","artistCredit":"The Chocolate Watch Band"},{"position":"2","title":"Too Many People","artistCredit":"The Leaves"},{"position":"3","title":"(Would I Still Be) Her Big Man","artistCredit":"The Brigands"},{"position":"4","title":"Are You a Boy or Are You a Girl","artistCredit":"The Barbarians"},{"position":"5","title":"Wooly Bully","artistCredit":"Sam the Sham & the Pharaohs"},{"position":"6","title":"I Want Candy","artistCredit":"The Strangeloves"},{"position":"7","title":"Louie Louie","artistCredit":"The Kingsmen"},{"position":"8","title":"One Track Mind","artistCredit":"The Knickerbockers"},{"position":"9","title":"Out of Our Tree","artistCredit":"The Wailers"},{"position":"10","title":"I Think I'm Down","artistCredit":"Harbinger Complex"},{"position":"11","title":"What Am I Going to Do","artistCredit":"The Dovers"},{"position":"12","title":"Codine","artistCredit":"The Charlatans"},{"position":"13","title":"Johnny Was a Good Boy","artistCredit":"The Mystery Trend"},{"position":"14","title":"Stop Get a Ticket","artistCredit":"Clefs of Lavender Hill"},{"position":"15","title":"Complication","artistCredit":"The Monks"},{"position":"16","title":"The Witch","artistCredit":"The Sonics"},{"position":"17","title":"Get Me to the World on Time","artistCredit":"The Electric Prunes"},{"position":"18","title":"Mr. Pharmacist","artistCredit":"The Other Half"},{"position":"19","title":"Open Up Your Door","artistCredit":"Richard and the Young Lions"},{"position":"20","title":"Just Like Me","artistCredit":"Paul Revere and the Raiders"},{"position":"21","title":"You Burn Me Up and Down","artistCredit":"We the People"},{"position":"22","title":"I Live in the Springtime","artistCredit":"The Lemon Drops"},{"position":"23","title":"Mindrocker","artistCredit":"Fenwyck"},{"position":"24","title":"Hold Me Now","artistCredit":"The Rumors"},{"position":"25","title":"Love's Gone Bad","artistCredit":"The Underdogs"},{"position":"26","title":"Why Pick on Me","artistCredit":"The Standells"},{"position":"27","title":"Bad Girl","artistCredit":"The Zakary Thaks"},{"position":"28","title":"Blackout of Gretely","artistCredit":"Gonn"},{"position":"29","title":"Voices Green and Purple","artistCredit":"The Bees"},{"position":"30","title":"Blue's theme","artistCredit":"Davie Allan & the Arrows"}]}
]""".trimIndent()) }